CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS REPORTING;

-----DIM_REVIEWER-----

create table curated.dim_reviewer (
reviewer_id varchar,
end_date date,
reviewer_name varchar,
start_date date,
ins_ts timestamp,
upd_ts timestamp);

create unique index idx_dim_reviwer on curated.dim_reviewer(reviewer_id,end_date);

-----FACT_PRODUCT_REVIEWS----

create table curated.fact_product_reviews (
product_review_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
reviewer_id varchar,
asin varchar,
helpful varchar,
review_text varchar,
summary varchar,
review_rating float,
review_date_id int,
raw_review_time timestamp,
ins_ts timestamp);



-----DIM_PRODUCT-----

create table curated.dim_product (
asin varchar,
end_date date,
title varchar,
description varchar,
category varchar,
raw_categories varchar,
price float,
price_bucket_id int,
sales_rank varchar,
imageurl varchar,
brand varchar,
related varchar,
start_date date,
ins_ts timestamp,
upd_ts timestamp);

create unique index idx_dim_product on curated.dim_product(asin,end_date);


---DIM_DATE
create table curated.dim_date (
date_id int,
date date,
day int,
month int,
year int );

with recursive date(date) as (
select '01-01-1970'::date
union all
select date+1 from date where date<'01-01-2100'::date)
insert into curated.dim_date select to_char(date,'YYYYMMDD')::int,date,to_char(date,'DD')::int,to_char(date,'MM')::int,to_char(date,'YYYY')::int from date;


-----DIM_PRICE_BUCKET-----------

create table curated.dim_price_bucket (
price_bucket_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1) ,
price_bucket varchar,
upper_limit float,
lower_limit float);

insert into curated.dim_price_bucket (price_bucket,lower_limit,upper_limit) values
('[0-100)$',0,100),
('[100-200)$',100,200),
('[200-300)$',200,300),
('[300-400)$',300,400),
('[400-500)$',400,500),
('[500-600)$',500,600),
('[600-700)$',600,700),
('[700-800)$',700,800),
('[800-900)$',800,900),
('[900-1000)$',900,1000),
('[1000-1100)$',1000,1100),
('[1100-1200)$',1000,1200);
